### ISSUE TITLE
VLP-16 poll timeout

### ISSUE THREAD

**Issue by hcv1027** [ros-drivers/velodyne#123] opened 2017-08-02 09:46 UTC
My working environment is Ubuntu 16.04 + ROS Kinect
I've followed the tutorial to setup VLP-16 connection, and I can open the VLP-16 user interface from my browser.
But there is no data shown in my rviz, use command "rostopic echo /velodyne_points" also got nothing.
After review the log, I find the warn message "_Velodyne poll() timeout_" is printed repeatedly.
This log is printed at the function _InputSocket::getPacket_ in file _input.cc_
Is there any solution for this problem?

**Comment by JWhitleyAStuff** [comment] 2017-11-06 20:19
Duplicate of #124

**Closed by JWhitleyAStuff** 2017-11-06 20:19 UTC
