### ISSUE TITLE
Supply URDF, Gazebo config?

### ISSUE THREAD

**Issue by mikepurvis** [ros-drivers/velodyne#32] opened 2014-09-26 03:44 UTC
Would this repository consider adding a `velodyne_description` package, with a xacro for spawning Velodyne sensors (especially the HDL-32e) into larger robot models? If so, I could work on preparing such a thing.

A simple example of something comparable would be the [`flir_ptu_description`](https://github.com/ros-drivers/flir_ptu/tree/master/flir_ptu_description/urdf) package available alongside the FLIR driver, which provides a macro for the popular D46 device.

**Comment by awesomebytes** [comment] 2015-03-09 12:10
Any light on this issue? I've been searching for some robot with a velodyne in it's model to start from that (or a magnificient velodyne_description itself) but I haven't found anything.

**Comment by mikepurvis** [comment] 2015-03-09 13:00
Alas, no progress from my side. Still interested in it, tho.

**Comment by jack-oquin** [comment] 2015-03-09 22:33
Me, either. I have no time for that kind of work these days.

**Comment by bmagyar** [comment] 2015-03-18 16:27
I'm working on it. The first version will be based on the MultiSenseSL (spinning hokuyo) to implement the Velodyne Puck. If there is interest we can talk further about the implementation.

**Comment by bmagyar** [comment] 2015-04-07 11:26
It is done. Give me a few days to prepare a proper PR and some story about it ;)

**Comment by jack-oquin** [comment] 2015-04-07 14:00
Thanks, @bmagyar, much appreciated!

**Comment by jack-oquin** [comment] 2015-08-06 16:39
@bmagyar: we are still interested in your packages, if they are available.

**Comment by bmagyar** [comment] 2015-08-06 21:33
Absolutely. I will try to cook something up this weekend / next week.

**Comment by kmhallen** [comment] 2015-12-02 01:55
I just made my work in this area available: https://bitbucket.org/DataspeedInc/velodyne_simulator

I think this should stay a separate repository so we don't bring in the gazebo_ros dependency.

I am open to suggestions and pull-requests.

Tested in Indigo and Jade.

**Comment by jack-oquin** [comment] 2015-12-02 15:49
That's great, @kmhallen. If you want to maintain it in a separate repository, that's fine with me.

The dependencies are not much of an issue, because users only need to install the packages they directly depend on, not the whole repository.

@mikepurvis, @bmagyar: Should we close this issue once velodyne_simulator gets released?

**Comment by bmagyar** [comment] 2015-12-02 20:48
Hi guys, sorry for the huge delay... I changed work and country again :)

I took a look at your solution. It looks good, but I didn't dig deep.


My first attempt btw was a model plugin that would spin a hokuyo fast enough to give the readings of a VLP16 but then I realized that numerically I'm over the rate of Gazebo :) 

Why did you implement your own plugin? I got away by using the block laser plugin, which was there, it's only that it had a minor bug for which the fix wasn't released at the moment. But it has been for a while now.

**Comment by kmhallen** [comment] 2015-12-02 21:29
The goal with the plugin was to generate data as closely to the velodyne_pointcloud package as possible.

Some changes from the block laser plugin

* Changed PointCloud to PointCloud2 with x, y, z, intensity, and ring
* Ranges greater than max were set to max. Now invalid ranges are skipped.
* Support changes to gazebo from indigo to jade (z orientation)
* Separate min and max ranges for gazebo ray-tracing and decision to include range or not. For example, don't include small ranges, but also stop the ray-tracing on collision with a close object.

I also plan to have an option to transform each range based on the time from start of scan. This will approximate a spinning laser to account for motion relative to some fixed frame.

**Comment by jack-oquin** [comment] 2015-12-02 23:15
According to REP-117, ranges greater than max should be set to +infinity.

**Comment by kmhallen** [comment] 2016-02-09 04:11
This will be available in the next sync.
http://wiki.ros.org/velodyne_simulator

**Comment by jack-oquin** [comment] 2016-02-09 14:45
Super! Many thanks @kmhallen.

**Comment by bmagyar** [comment] 2016-02-09 14:49
:+1:

**Comment by jack-oquin** [comment] 2016-02-10 16:59
Closing this, as the problem is solved in the [velodyne_simulator](http://wiki.ros.org/velodyne_simulator) repository by @kmhallen.

Thanks to you all for helping with this.

cc: @piyushk

**Closed by jack-oquin** 2016-02-10 16:59 UTC
